name: CI

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install hyperscan
        run: sudo apt-get install -y libhyperscan-dev

      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build

      - name: Build in Release
        run: zig build -Drelease-fast
